image:
  file: .gitpod.Dockerfile

tasks:
  - init: pip install -r requirements.txt
    command: echo "✅ All dependencies installed"

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
